name: 'Setup DDEV in Github Workflows'
description: |
  This action installs **DDEV** in your Github Workflow.
  It's main use case is to run your Continuous Integration
  tests against your already configured development environment. 
  That'll facilitate developing your tests – if they run locally, 
  they'll run in github actions, too.
author: 'Jonas Eberle and DDEV contributors'
runs:
  using: 'node16'
  main: 'lib/main.js'
branding:
  icon: cpu
  color: yellow
inputs:
  ddevDir:
    description: 'ddev project directory'
    required: false
    default: '.'
  autostart:
    description: 'Start ddev automatically'
    required: false
    default: true
