name: 'Setup DDEV in Github Workflows'
description: |
  This action installs **DDEV** in your Github Workflow.
author: 'Jonas Eberle and DDEV contributors'
runs:
  using: 'node16'
  main: 'lib/main.js'
branding:
  icon: cpu
  color: yellow
inputs:
  ddevDir:
    description: 'ddev project directory'
    required: false
    default: '.'
  autostart:
    description: 'Start ddev automatically'
    required: false
    default: true
