on: [push, pull_request]

jobs:
  test-setup-ddev:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
    steps:
      - uses: actions/checkout@v1
      - name: Setup ddev
        id: setup-ddev
        uses: jonaseberle/github-action-setup-ddev@master